### ISSUE TITLE
Kanban board review 

### ISSUE THREAD

**Issue by Ofarouq310** [ZuhRa-HashiMi/JS_Capastone#21]
### **Project link:** https://github.com/ZuhRa-HashiMi/JS_Capastone/projects/1
 _Note: Our group consists of 3 people._

**Comment by BregornOriginal** [comment]
## Hi @Team 💯 💯 💯 

## Good job so far! 👏🏼 👏🏼 👏🏼 
## There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️


***Please assign the card's activities to each student. So in this way, each of the students would know which task corresponds to him and you can check your history work on the kanban board.***

![image](https://user-images.githubusercontent.com/93630700/204333093-58c69bc6-7748-4f3a-b12f-44d099d8b98d.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aimalamiri** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ApprovedDavieGIF](https://user-images.githubusercontent.com/34779928/191333120-c0c2ce83-28e1-4dbc-aac1-09e467f7a8bd.gif)


## Highlights

- The Kanban board is setup properly ✔️ ⭐
- The tasks are assigned to the teams 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
